//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GereCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilhete
    {
        public int IdBilhete { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int SessaoIdSessao { get; set; }
        public int VendaIdVenda { get; set; }
    
        public virtual Sessao Sessao { get; set; }
        public virtual Venda Venda { get; set; }
    }
}
