//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GereCinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaDBContainer : DbContext
    {
        public CinemaDBContainer()
            : base("name=CinemaDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
        public virtual DbSet<Venda> Vendas { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Sala> Salas { get; set; }
        public virtual DbSet<Filme> Filmes { get; set; }
        public virtual DbSet<Sessao> Sessoes { get; set; }
        public virtual DbSet<Lugar> Lugares { get; set; }
        public virtual DbSet<Bilhete> Bilhetes { get; set; }
    }
}
